resource_group_name = "tp-rg"
resource_group_name2 = "tp-rg2"
location            = "centralindia"
storage_account_name="tpterrastorage"
storage_container_name="tpterrastoragedata"
storage_account_name2="tpterrastorag2"
storage_container_name2="tpterrastoragedata2"